project:
  type: website

website:
  title: "Statistical Rethinking 2 in PyMC"
#  navbar:
#    right:
#      - about.qmd
#      - icon: github
#        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com
sidebar:
  style: "docked"
  search: true
  contents:
  - section: "Rethinking"
    contents:
    - chapters/chapter_02.ipynb
format:
  html:
    theme: cosmo
    css: styles.css



