project:
  type: website

website:
  title: "Statistical Rethinking 2 in PyMC"
#  navbar:
#    right:
#      - about.qmd
#      - icon: github
#        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com
sidebar:
  style: "docked"
  search: true
  contents:
    - section: "Chapters"
      contents: chapters/*
  tools:
    - icon: github
      menu: 
        - text: Source Code
          url: https://github.com/mdmanurung/rethinking-pymc
format:
  html:
    theme: cosmo
    css: styles.css



