# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/rethinking-pymc',
                'doc_host': 'https://mdmanurung.github.io',
                'git_url': 'https://github.com/mdmanurung/rethinking-pymc',
                'lib_path': 'rethinking_pymc'},
  'syms': {'rethinking_pymc.core': {'rethinking_pymc.core.foo': ('core.html#foo', 'rethinking_pymc/core.py')}}}